version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - MODE=local

  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: portal
      POSTGRES_DB: supplier_db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/supplier_db
      KC_DB_USERNAME: portal
      KC_DB_PASSWORD: portal
    depends_on:
      - postgres

  redpanda:
    image: vectorized/redpanda:latest
    ports:
      - "9092:9092"
    command:
      [
        "redpanda",
        "start",
        "--overprovisioned",
        "--smp",
        "1",
        "--memory",
        "1G",
        "--reserve-memory",
        "0M",
      ]
